apiVersion: v1
kind: Service
metadata:
  name: kubenodeapp-service
  namespace: kubenodeapp
spec:
  type: LoadBalancer
  selector:
    app: kubenodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000